### ISSUE TITLE
ImportError: No module named lxml

### ISSUE THREAD

**Issue by Rayman** [ros/urdf_parser_py#51] opened 2019-11-06 09:26 UTC
After yesterday's sync, this package doesn't install it's dependencies on lxml and yaml.

```apt update
apt install -y ros-melodic-urdfdom-py

python -c 'import urdf_parser_py.urdf'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/ros/melodic/lib/python2.7/dist-packages/urdf_parser_py/urdf.py", line 1, in <module>
    from urdf_parser_py.xml_reflection.basics import *
  File "/opt/ros/melodic/lib/python2.7/dist-packages/urdf_parser_py/xml_reflection/__init__.py", line 1, in <module>
    from urdf_parser_py.xml_reflection.core import *
  File "/opt/ros/melodic/lib/python2.7/dist-packages/urdf_parser_py/xml_reflection/core.py", line 1, in <module>
    from urdf_parser_py.xml_reflection.basics import *
  File "/opt/ros/melodic/lib/python2.7/dist-packages/urdf_parser_py/xml_reflection/basics.py", line 4, in <module>
    from lxml import etree
ImportError: No module named lxml
```
If you look at the dependencies of the debian package, it is missing 2 of them. Are the condition tags parsed properly?
```
apt depends ros-melodic-urdfdom-py
ros-melodic-urdfdom-py
  Depends: ros-melodic-rospy
```

**Comment by fmessmer** [comment] 2019-11-08 07:04
experiencing the same running travis tests

I guess it was caused by https://github.com/ros/urdf_parser_py/commit/87b2913d5b5cc06178569191e33b5fded2675b13#diff-34ae68f4adad56c25c5bc05dcb64794e

**Comment by Rayman** [comment] 2019-11-08 09:48
I think this package is released with old bloom tooling.

If you look at ros_comm, the package xml looks [like this](https://github.com/ros/ros_comm/blob/5da095d06bccbea708394b399215d8a066797266/tools/rosmsg/package.xml) and after releasing [the condition tags are resolved](https://github.com/ros-gbp/ros_comm-release/blob/ae796d44abec751f2f575c196fb285813ec699fd/package.xml).

When I look at [urdfdom_py](https://github.com/ros-gbp/urdfdom_py-release/blob/ea592fa4faca7dc7dc065d0a62537dbcc7148c5e/package.xml) the condition tags have not been resolved after releasing with bloom.

@sloretz, is it possible to test releasing this package with bloom 0.9.0?

**Comment by sloretz** [comment] 2019-11-08 18:38
> @sloretz, is it possible to test releasing this package with bloom 0.9.0?

Used bloom 0.9.0 to release 0.4.1-2 in https://github.com/ros/rosdistro/pull/22921

Looks like [lxml and yaml are now listed as dependencies](
https://github.com/ros-gbp/urdfdom_py-release/blob/e8e433d3194e3cc46411224e12211f5165c8fdd1/debian/control#L11).

**Comment by Rayman** [comment] 2019-11-11 09:53
Thanks!

**Comment by sloretz** [comment] 2019-11-11 17:37
Looks like `lxml` and `yaml` are listed as dependencies in [ros-testing](http://packages.ros.org/ros-testing/ubuntu/dists/bionic/main/binary-amd64/Packages), so I'll close this issue for now. It should be fixed in the next sync.

```

Package: ros-melodic-urdfdom-py
Version: 0.4.1-2bionic.20191109.013217
Architecture: amd64
Maintainer: Chris Lalancette <clalancette@osrfoundation.org>
Installed-Size: 150
Depends: python-lxml, python-yaml, ros-melodic-rospy
Homepage: http://wiki.ros.org/urdfdom_py
Priority: optional
Section: misc
Filename: pool/main/r/ros-melodic-urdfdom-py/ros-melodic-urdfdom-py_0.4.1-2bionic.20191109.013217_amd64.deb
Size: 31720
SHA256: 16e1acf13815bf96d4fcc53b90c89a5185259959b7299395da3d165e7e3f7f01
SHA1: a0db3d31832c814da041e4d1c809f11bb24b44f7
MD5sum: e21d75614aac5627382c0f031b71fd19
Description: Python implementation of the URDF parser.
```

**Closed as completed by sloretz** 2019-11-11 17:37 UTC
