### ISSUE TITLE
"Unknown tag: hardwareInterface" in actuator

### ISSUE THREAD

**Issue by 130s** [ros/urdf_parser_py#6] opened 2016-08-25 20:16 UTC
I'm not sure, but there's a potential regression during runtime.

I started getting an error with one of our robots (software undisclosable):

```
Unknown tag: hardwareInterface
Unknown tag: hardwareInterface
Unknown tag: hardwareInterface
Unknown tag: hardwareInterface
Unknown tag: hardwareInterface
Unknown tag: hardwareInterface
Unknown tag: hardwareInterface
Unknown tag: hardwareInterface
Unknown tag: hardwareInterface
Unknown tag: hardwareInterface
:
```

The tags in question are probably the ones defined in `actuator` tag. And I suspect that this has begun happening after [this commit](https://github.com/ros/urdf_parser_py/commit/e0a05c729fc76d8bf02fe32e5b36a85b5151bcc5#diff-8311b358bd6b51da837a7ec89b99b130).

To check with simpler case, [in my forked repo](https://github.com/130s/urdf_parser_py/pull/1) I added `hardwareInterface` in an actuator element in the test case, and the [test fails](https://travis-ci.org/130s/urdf_parser_py/builds/155157332#L166) returning the same error.

[Definition on the wiki](http://wiki.ros.org/urdf/XML/Transmission#A.3Ctransmission.3E_Elements) says `hardwareInterface` can be optionally defined in actuator. So something is wrong with the current impl.

**Comment by 130s** [comment] 2016-08-25 20:17
Can @rhaschke take a look since you've made the change? Thanks!

**Comment by rhaschke** [comment] 2016-09-14 22:09
Hm. I'm pretty sure, that at the time I proposed that change, the [URDF spec](http://wiki.ros.org/urdf/XML/Transmission#A.3Ctransmission.3E_Elements) marked the `hardwareInterface` in the `<actuator>` tag as deprecated, which was verified by @jacquelinekay in https://github.com/ros/urdfdom/pull/68#issuecomment-163369283. Did the spec changed since then?

**Comment by clalancette** [comment] 2017-02-09 00:10
http://wiki.ros.org/urdf/XML/Transmission#A.3Ctransmission.3E_Elements says:

<actuator> (one or more occurrences) 
    <hardwareInterface> (optional) (one or more occurrences)
        Specifies a supported joint-space hardware interface. Note that <hardwareInterface> tag should only be specified here for ROS releases prior to Indigo.  The correct place to specify this tag is in <joint> tag.

So I believe that this is expected behavior on Indigo and later, and that the hardwareInterface tag should be specified against the joint, not the actuator.  I'm going to close this out for now, but please re-open if you have good reasons to suspect otherwise.

**Closed as completed by clalancette** 2017-02-09 00:10 UTC
